name: Generate lowlighter
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Full-year calendar
    uses: lowlighter/metrics@latest
    with:
      filename: metrics.plugin.isocalendar.fullyear.svg
      token: ${{ secrets.METRICS_TOKEN }}
      base: ""
      plugin_isocalendar: yes
      plugin_isocalendar_duration: half-year
